Add fname, lname, email
wedoforce/students pull request #15
Opened 2022-02-05 11:55 UTC by ArtsiomDev

Add 1 line with personal data.

2022-02-05 14:32 UTC, ArtsiomDev commented
1111

2022-02-06 10:38 UTC, OleJoMan requested changes
resolve conflicts

2022-02-06 19:59 UTC, baksale commented
There are conflicts still.
Do you see this button?
![image](https://user-images.githubusercontent.com/33149951/152699089-0664bb04-a6de-4957-8ba7-28bf2f446279.png)

2022-02-06 20:05 UTC, ArtsiomDev commented
> 

Yes, but I can't figure out how to fix it.

2022-02-06 20:40 UTC, closed without merging