add name and email
wedoforce/students pull request #22
Opened 2022-02-06 00:53 UTC by Azamat-Molodes

2022-02-06 10:30 UTC, OleJoMan requested changes
resolve conflict

2022-02-06 21:48 UTC, Zhalyn approved these changes

2022-02-07 05:32 UTC, baksale commented
You need to resolve conflicts - ask team to help you.

2022-02-07 14:17 UTC, closed without merging

2022-02-07 14:39 UTC, Zhalyn approved these changes

2022-02-07 14:40 UTC, Zhalyn commented
me too think this last time)